### ISSUE TITLE
Wrong link on Flexbox 2nd post

### ISSUE THREAD

**Issue by amitaibu** [guytepper/devhead.co.il#1]
Great [post](http://devhead.co.il/flexbox-part-2) and the code pens are very handy.

One link seems to direct to your local :)

![flexbox_-_ _ _-_ _](https://cloud.githubusercontent.com/assets/125707/14411689/39fd76ae-ff58-11e5-9540-8b75d53e55e2.jpg)

**Comment by guytepper** [comment]
Thanks for reporting!
