### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by eyalcohen4** [guytepper/devhead.co.il#2]
hey man, look at your git after hasdna yestarday, i am eyal from  the open_pension front-end team.
the three  articles in the blog are great! the flex-box is still something i need to practice about, and a good content in hebrew is always great.

my eyes catch one spelling mistake in the flex-box first part...

![you wrote מפתחת instead of מפתח](https://cloud.githubusercontent.com/assets/16276358/16419405/3d094aa8-3d56-11e6-81a7-4adef13faa4e.png)

**Comment by guytepper** [comment]
Hi dude!
Thanks for the kind words. Means a lot. I totally abandoned writing and really need to do it more.
Regarding the spelling mistake.. This is not a mistake! 😁 It's just a female developer (-:
